# Generated by Django 3.2.3 on 2022-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=32, unique=True, verbose_name='文章标题')),
                ('active_label', models.CharField(choices=[('notice', '公告'), ('strategy', '攻略'), ('talk', '趣谈')], max_length=20, unique=True, verbose_name='文章类型')),
                ('article_img', models.ImageField(upload_to='', verbose_name='文章封面图')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('article_uptime', models.DateTimeField(verbose_name='发布时间')),
                ('user_id', models.CharField(max_length=50, verbose_name='发布者ID')),
                ('article_views', models.FloatField(default=0, verbose_name='文章浏览量')),
                ('article_fabulous', models.FloatField(default=0, verbose_name='文章点赞数')),
                ('article_collection', models.FloatField(default=0, verbose_name='文章收藏数')),
                ('article_forward', models.FloatField(default=0, verbose_name='文章转发数')),
                ('article_comments_num', models.FloatField(default=0, verbose_name='文章评论数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
            },
        ),
    ]
