# Generated by Django 3.2.3 on 2022-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_active_label_article_article_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.TextField(verbose_name='文章封面图'),
        ),
    ]
