# Generated by Django 3.2.3 on 2022-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_article_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_label',
            field=models.CharField(choices=[('notice', '公告'), ('strategy', '攻略'), ('talk', '趣谈')], max_length=20, verbose_name='文章类型'),
        ),
    ]
