# Generated by Django 3.2.3 on 2022-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_article_fabulous_article_article_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user_id',
            field=models.FloatField(max_length=50, verbose_name='发布者ID'),
        ),
    ]
