# Generated by Django 3.2.3 on 2022-03-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_label',
            field=models.CharField(default='comment', max_length=20, verbose_name='被评论类型(文章/评论)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='article_id',
            field=models.CharField(max_length=20, verbose_name='被评论文章/评论id'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='评论id'),
        ),
    ]
