# Generated by Django 3.2.3 on 2022-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20220324_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_like',
            field=models.PositiveIntegerField(default=0, verbose_name='评论点赞数'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_reply',
            field=models.PositiveIntegerField(default=0, verbose_name='评论回复数'),
        ),
    ]
