# Generated by Django 3.2.3 on 2022-03-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fans',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='browsing_history',
            field=models.CharField(default=0, max_length=100, verbose_name='浏览历史数'),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_num',
            field=models.CharField(default=0, max_length=100, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank='null', max_length=20, verbose_name='兴趣'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_collection',
            field=models.CharField(default=0, max_length=100, verbose_name='用户收藏数'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_fans_num',
            field=models.CharField(default=0, max_length=100, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_head',
            field=models.ImageField(default='https://img0.baidu.com/it/u=324179460,1196659069&fm=253&fmt=auto&app=138&f=JPEG?w=400&h=400', upload_to='', verbose_name='用户头像'),
        ),
    ]
