# Generated by Django 3.2.3 on 2022-03-10 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220307_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True, verbose_name='生日'),
        ),
    ]
