# Generated by Django 3.2.3 on 2022-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.TextField(default='https://img0.baidu.com/it/u=324179460,1196659069&fm=253&fmt=auto&app=138&f=JPEG?w=400&h=400', verbose_name='用户头像'),
        ),
    ]
