# Generated by Django 3.2.3 on 2022-03-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=30, verbose_name='兴趣'),
        ),
    ]
