# Generated by Django 3.2.3 on 2022-03-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户ID')),
                ('is_collection', models.BooleanField(verbose_name='是否收藏')),
                ('article_id', models.CharField(max_length=20, verbose_name='文章ID')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_collection',
            },
        ),
    ]
