# Generated by Django 3.2.3 on 2022-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220317_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户ID')),
                ('is_Like', models.BooleanField(verbose_name='是否喜欢')),
                ('article_id', models.CharField(max_length=20, verbose_name='文章ID')),
            ],
            options={
                'verbose_name': '用户喜欢',
                'verbose_name_plural': '用户喜欢',
                'db_table': 'user_like',
            },
        ),
    ]
