# Generated by Django 3.2.3 on 2022-03-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='is_Like',
            new_name='is_like',
        ),
    ]
