# Generated by Django 3.2.3 on 2022-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_is_like_userlike_is_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户ID')),
                ('is_follow', models.BooleanField(verbose_name='是否关注')),
                ('follow_user_id', models.CharField(max_length=20, verbose_name='被关注用户ID')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'user_follow',
            },
        ),
    ]
